apiVersion: v1
kind: Pod
metadata:
  name: nginx-linux-namespace-pod
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
  - name: shell
    image: busybox
    stdin: true
    tty: true