apiVersion: v1
kind: Pod
metadata:
  name: test-secret-projected-volume
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: mysql-cred
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: mysql-cred
    secret:
      secretName: mysql-secret